vich_uploader:
    db_driver: orm

    mappings:
        bottle_picture:
            uri_prefix: /img/
            upload_destination: '%kernel.project_dir%/public/img'
            namer: Vich\UploaderBundle\Naming\UniqidNamer